-- BuddyList GTM plan schema + security
-- Run this in Supabase SQL Editor as a privileged role.

begin;

-- Keep away messages on the existing users table.
alter table public.users
  add column if not exists status_msg text default 'Available';

-- Shared trigger for updated_at timestamps.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.buddies (
  user_id uuid not null references public.users(id) on delete cascade,
  buddy_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, buddy_id),
  constraint buddies_not_self check (user_id <> buddy_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.users(id) on delete cascade,
  receiver_id uuid not null references public.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists buddies_user_idx on public.buddies (user_id);
create index if not exists buddies_buddy_idx on public.buddies (buddy_id);
create index if not exists buddies_status_idx on public.buddies (status);
create index if not exists messages_sender_receiver_created_idx
  on public.messages (sender_id, receiver_id, created_at desc);
create index if not exists messages_receiver_created_idx
  on public.messages (receiver_id, created_at desc);

drop trigger if exists buddies_set_updated_at on public.buddies;
create trigger buddies_set_updated_at
before update on public.buddies
for each row
execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.buddies enable row level security;
alter table public.messages enable row level security;

drop policy if exists users_select_profiles on public.users;
create policy users_select_profiles
on public.users
for select
to authenticated
using (true);

drop policy if exists users_insert_own on public.users;
create policy users_insert_own
on public.users
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists users_update_own on public.users;
create policy users_update_own
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists buddies_select_own_or_related on public.buddies;
create policy buddies_select_own_or_related
on public.buddies
for select
to authenticated
using (auth.uid() = user_id or auth.uid() = buddy_id);

drop policy if exists buddies_insert_own_or_related on public.buddies;
create policy buddies_insert_own_or_related
on public.buddies
for insert
to authenticated
with check (auth.uid() = user_id or auth.uid() = buddy_id);

drop policy if exists buddies_update_own_or_related on public.buddies;
create policy buddies_update_own_or_related
on public.buddies
for update
to authenticated
using (auth.uid() = user_id or auth.uid() = buddy_id)
with check (auth.uid() = user_id or auth.uid() = buddy_id);

drop policy if exists buddies_delete_own_or_related on public.buddies;
create policy buddies_delete_own_or_related
on public.buddies
for delete
to authenticated
using (auth.uid() = user_id or auth.uid() = buddy_id);

drop policy if exists messages_select_participants on public.messages;
create policy messages_select_participants
on public.messages
for select
to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists messages_insert_participants on public.messages;
create policy messages_insert_participants
on public.messages
for insert
to authenticated
with check (auth.uid() = sender_id or auth.uid() = receiver_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'buddies'
  ) then
    alter publication supabase_realtime add table public.buddies;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'users'
  ) then
    alter publication supabase_realtime add table public.users;
  end if;
end;
$$;

commit;
