-- Non-email password recovery with admin fallback tickets
-- Run this in Supabase SQL Editor as a privileged role.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.account_recovery_codes (
  user_id uuid primary key references public.users(id) on delete cascade,
  code_hash text not null,
  code_salt text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  rotated_at timestamptz null
);

create table if not exists public.password_reset_attempts (
  screenname_key text not null,
  ip_hash text not null,
  attempt_count int not null default 0,
  window_started_at timestamptz not null default timezone('utc', now()),
  locked_until timestamptz null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (screenname_key, ip_hash)
);

create table if not exists public.admin_users (
  user_id uuid primary key references public.users(id) on delete cascade,
  screenname text not null,
  created_at timestamptz not null default timezone('utc', now()),
  created_by uuid null references public.users(id)
);

create table if not exists public.password_reset_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  issued_by uuid not null references public.users(id) on delete restrict,
  ticket_hash text not null,
  ticket_salt text not null,
  expires_at timestamptz not null,
  used_at timestamptz null,
  revoked_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.password_reset_audit (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_user_id uuid null references public.users(id) on delete set null,
  target_user_id uuid null references public.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists password_reset_tickets_user_idx
  on public.password_reset_tickets (user_id);

create index if not exists password_reset_tickets_expires_idx
  on public.password_reset_tickets (expires_at);

create index if not exists password_reset_tickets_active_idx
  on public.password_reset_tickets (user_id, expires_at)
  where used_at is null and revoked_at is null;

create index if not exists password_reset_audit_created_idx
  on public.password_reset_audit (created_at desc);

drop trigger if exists account_recovery_codes_set_updated_at on public.account_recovery_codes;
create trigger account_recovery_codes_set_updated_at
before update on public.account_recovery_codes
for each row
execute function public.set_updated_at();

drop trigger if exists password_reset_attempts_set_updated_at on public.password_reset_attempts;
create trigger password_reset_attempts_set_updated_at
before update on public.password_reset_attempts
for each row
execute function public.set_updated_at();

alter table public.account_recovery_codes enable row level security;
alter table public.password_reset_attempts enable row level security;
alter table public.admin_users enable row level security;
alter table public.password_reset_tickets enable row level security;
alter table public.password_reset_audit enable row level security;

drop policy if exists account_recovery_codes_select_own on public.account_recovery_codes;
create policy account_recovery_codes_select_own
on public.account_recovery_codes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists account_recovery_codes_insert_own on public.account_recovery_codes;
create policy account_recovery_codes_insert_own
on public.account_recovery_codes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists account_recovery_codes_update_own on public.account_recovery_codes;
create policy account_recovery_codes_update_own
on public.account_recovery_codes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists admin_users_select_own on public.admin_users;
create policy admin_users_select_own
on public.admin_users
for select
to authenticated
using (auth.uid() = user_id);

commit;
