require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.pods_project.targets.each do |target|
    target.build_phases.each do |phase|
      next unless phase.respond_to?(:name) && phase.name == '[CP] Copy XCFrameworks'

      # Xcode 14+: marks the script as always out of date
      # (unchecked "Based on dependency analysis")
      if phase.respond_to?(:always_out_of_date)
        phase.always_out_of_date = '1'
      end

      # Older Xcode versions may use this flag name.
      if phase.respond_to?(:based_on_dependency_analysis)
        phase.based_on_dependency_analysis = '0'
      end
    end
  end
end
